// Reads assets/WasteNoSpaceGui.png (the CC0 "Waste No Space" 64x64 GUI sheet),
// crops the 9-patch regions UiSkin.cs names (Godot stylebox rects, y from top),
// and writes src/patches.ts with each patch as a tiny data-URI PNG.
// Pure node: zlib for inflate/deflate, hand-rolled PNG chunk IO.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import zlib from 'node:zlib';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const bytes = readFileSync(join(root, 'assets/WasteNoSpaceGui.png'));

// ---- decode ----
const u32 = (o) => bytes.readUInt32BE(o);
let off = 8;
let ihdr = null, plte = null, trns = null;
const idat = [];
while (off < bytes.length) {
  const len = u32(off), type = bytes.toString('ascii', off + 4, off + 8);
  const data = bytes.subarray(off + 8, off + 8 + len);
  if (type === 'IHDR') ihdr = data;
  else if (type === 'PLTE') plte = data;
  else if (type === 'tRNS') trns = data;
  else if (type === 'IDAT') idat.push(data);
  off += 12 + len;
}
const W = ihdr.readUInt32BE(0), H = ihdr.readUInt32BE(4);
const depth = ihdr[8], colour = ihdr[9];
if (depth !== 8) throw new Error('expected 8-bit');
const raw = zlib.inflateSync(Buffer.concat(idat));
const channels = colour === 6 ? 4 : colour === 2 ? 3 : 1;
const stride = W * channels;

// defilter
const img = Buffer.alloc(H * stride);
for (let y = 0; y < H; y++) {
  const f = raw[y * (stride + 1)];
  const line = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1));
  const prev = y > 0 ? img.subarray((y - 1) * stride, y * stride) : null;
  const out = img.subarray(y * stride, (y + 1) * stride);
  for (let x = 0; x < stride; x++) {
    const a = x >= channels ? out[x - channels] : 0;
    const b = prev ? prev[x] : 0;
    const c = x >= channels && prev ? prev[x - channels] : 0;
    let v = line[x];
    if (f === 1) v += a;
    else if (f === 2) v += b;
    else if (f === 3) v += (a + b) >> 1;
    else if (f === 4) {
      const p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
      v += pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
    }
    out[x] = v & 0xff;
  }
}

const rgbaAt = (x, y) => {
  if (colour === 3) {
    const i = img[y * stride + x];
    return [plte[i * 3], plte[i * 3 + 1], plte[i * 3 + 2], trns && i < trns.length ? trns[i] : 255];
  }
  const o = y * stride + x * channels;
  return colour === 6
    ? [img[o], img[o + 1], img[o + 2], img[o + 3]]
    : [img[o], img[o + 1], img[o + 2], 255];
};

// ---- encode a crop ----
const crc = (buf) => {
  let c = ~0;
  for (const b of buf) {
    c ^= b;
    for (let i = 0; i < 8; i++) c = (c >>> 1) ^ (0xedb88320 & -(c & 1));
  }
  return ~c >>> 0;
};
const chunk = (type, data) => {
  const out = Buffer.alloc(12 + data.length);
  out.writeUInt32BE(data.length, 0);
  out.write(type, 4, 'ascii');
  data.copy(out, 8);
  out.writeUInt32BE(crc(out.subarray(4, 8 + data.length)), 8 + data.length);
  return out;
};
function encode(x0, y0, w, h) {
  const rows = Buffer.alloc(h * (w * 4 + 1));
  for (let y = 0; y < h; y++)
    for (let x = 0; x < w; x++) {
      const [r, g, b, a] = rgbaAt(x0 + x, y0 + y);
      const o = y * (w * 4 + 1) + 1 + x * 4;
      rows[o] = r; rows[o + 1] = g; rows[o + 2] = b; rows[o + 3] = a;
    }
  const head = Buffer.alloc(13);
  head.writeUInt32BE(w, 0); head.writeUInt32BE(h, 4);
  head[8] = 8; head[9] = 6;
  const png = Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', head),
    chunk('IDAT', zlib.deflateSync(rows, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
  return `data:image/png;base64,${png.toString('base64')}`;
}

// UiSkin.cs region_rects: x, yFromTop, w, h - all 5x5 with a 2px frame.
const patches = {
  panelDark: encode(7, 7, 5, 5),
  panelRaised: encode(7, 25, 5, 5),
  sunken: encode(1, 31, 5, 5),
  buttonNormal: encode(1, 25, 5, 5),
  buttonHover: encode(1, 13, 5, 5),
  buttonPressed: encode(1, 31, 5, 5),
  buttonDisabled: encode(1, 1, 5, 5),
};

const ts = `// GENERATED by tools/extract-patches.mjs - do not edit.
// 5x5 9-patch chrome off the CC0 "Waste No Space" GUI sheet (flatus.itch.io).
export const patches = ${JSON.stringify(patches, null, 2)} as const;
`;
mkdirSync(join(root, 'src'), { recursive: true });
writeFileSync(join(root, 'src/patches.ts'), ts);
console.log('patches written:', Object.keys(patches).join(', '));
