// GENERATED by Tools/City/Residential/Bake Named Buildings.
// Every figure here was measured off the buildings named residential1..N in
// Assets/Scenes/CoreHarvest.unity. Do not edit by hand - re-run the harvest.
//
// A plan row reads west to east; the FIRST row is the NORTH edge, so the table
// looks the way the block looks from above with north up.
//   '#' the building stands on this cell   'f' its own forecourt: stoop, pit, garden
//   ':' forecourt that drops below -0.6 m (no floor slab under it)
//   ',' building whose own cell drops below -0.6 m
//   '.' nothing - the block's to use

namespace RoadDemo
{
    /// <summary>What a residential unit is: its footprint on the 5 m raster, which
    /// of its sides open onto a street, and what hangs over the pavement.</summary>
    public sealed class ResidentialUnit
    {
        public string Name;
        public int CW, CD;
        /// <summary>North row first, west to east. See the key at the top of this file.</summary>
        public string[] Plan;
        /// <summary>South, east, north, west.</summary>
        public bool[] Face;
        public int[] Doors, Shops, Stoops;
        /// <summary>What reaches out past the footprint on each side, metres.</summary>
        public float[] Over;
        public int Trees, Pieces;
        public float MaxH;
        public ResidentialKind Kind;

        public bool Wall(int i, int j) => At(i, j) == '#' || At(i, j) == ',';
        public bool Yard(int i, int j) => At(i, j) == 'f' || At(i, j) == ':';
        public bool Pit(int i, int j) => At(i, j) == ':' || At(i, j) == ',';
        public bool Filled(int i, int j) => At(i, j) != '.';

        /// <summary>The cell at (i east, j north), reading the plan bottom row first.</summary>
        char At(int i, int j) =>
            i < 0 || j < 0 || i >= CW || j >= CD ? '.' : Plan[CD - 1 - j][i];
    }

    public enum ResidentialKind { Row, Corner, Through, Island }

    public static class ResidentialUnits
    {
        public static readonly ResidentialUnit[] All =
        {
            new ResidentialUnit
            {
                Name = "residential-01", CW = 5, CD = 4,
                Kind = ResidentialKind.Corner,
                MaxH = 15.6f, Trees = 0, Pieces = 154,
                Plan = new[]
                {
                    "#####",
                    "#####",
                    "##...",
                    "##...",
                },
                Face = new[] { false, false, true, true },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 0, 1, 3, 4 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 0.73f, 0.47f, 1.97f, 2.03f },
            },
            new ResidentialUnit
            {
                Name = "residential-02", CW = 8, CD = 5,
                Kind = ResidentialKind.Corner,
                MaxH = 18.6f, Trees = 0, Pieces = 273,
                Plan = new[]
                {
                    "##......",
                    "##......",
                    "##......",
                    "####.###",
                    "########",
                },
                Face = new[] { true, false, false, true },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 6, 1, 1, 3 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.76f, 1.76f, 0.46f, 1.68f },
            },
            new ResidentialUnit
            {
                Name = "residential-03", CW = 9, CD = 5,
                Kind = ResidentialKind.Corner,
                MaxH = 18.6f, Trees = 0, Pieces = 306,
                Plan = new[]
                {
                    "##.......",
                    "##.......",
                    "##.......",
                    "#########",
                    "#########",
                },
                Face = new[] { true, false, false, true },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 7, 1, 1, 3 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 3.25f, 1.76f, 0.73f, 1.76f },
            },
            new ResidentialUnit
            {
                Name = "residential-04", CW = 5, CD = 5,
                Kind = ResidentialKind.Corner,
                MaxH = 15.2f, Trees = 6, Pieces = 111,
                Plan = new[]
                {
                    ":::::",
                    "####:",
                    "####:",
                    "..##:",
                    "..##:",
                },
                Face = new[] { false, true, true, false },
                Doors = new[] { 1, 3, 3, 0 },
                Shops = new[] { 0, 0, 0, 0 },
                Stoops = new[] { 0, 5, 3, 0 },
                Over = new[] { 1.14f, 0.13f, 0.13f, 1.76f },
            },
            new ResidentialUnit
            {
                Name = "residential-05", CW = 4, CD = 9,
                Kind = ResidentialKind.Through,
                MaxH = 16.7f, Trees = 4, Pieces = 126,
                Plan = new[]
                {
                    "::::",
                    ":##:",
                    ":##:",
                    ":##:",
                    ":##:",
                    ":##:",
                    ":##:",
                    ":##:",
                    "::::",
                },
                Face = new[] { false, true, false, true },
                Doors = new[] { 1, 6, 1, 6 },
                Shops = new[] { 0, 0, 0, 0 },
                Stoops = new[] { 1, 6, 1, 8 },
                Over = new[] { 0.00f, 0.13f, 0.00f, 0.13f },
            },
            new ResidentialUnit
            {
                Name = "residential-06", CW = 10, CD = 9,
                Kind = ResidentialKind.Corner,
                MaxH = 18.2f, Trees = 0, Pieces = 236,
                Plan = new[]
                {
                    "##########",
                    "##########",
                    "........##",
                    "........##",
                    "........##",
                    ".........#",
                    "........##",
                    "........##",
                    "........##",
                },
                Face = new[] { false, true, true, false },
                Doors = new[] { 0, 4, 2, 0 },
                Shops = new[] { 1, 4, 6, 1 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.76f, 1.76f, 1.76f, 0.27f },
            },
        };
    }
}
