// GENERATED by unity command gangsters_module_atlas. Do not edit by hand.
using System;

namespace RoadDemo
{
    public enum ResidentialModuleKind { Unknown, Shop, ShopCorner, ShopCover, Apartment, ApartmentStack, ApartmentCorner, ApartmentDoor, Roof, RoofCorner, RoofAccess, FireEscape, Decor }

    public sealed class ResidentialModule
    {
        public string Name, Path;
        public ResidentialModuleKind Kind;
        public float MinX, MinY, MinZ, MaxX, MaxY, MaxZ;
        public int Faces, Style, Cells, Floors;
        public bool OuterCorner;
        public int RoofPairStyle, EscapeOrder;
        public float DoorX, DoorZ, DoorWidth, DoorHeight, DoorYaw;
        public int DoorLeaves;
    }

    public static class ResidentialModules
    {
        public const int FacePlusZ = 1, FacePlusX = 2, FaceMinusZ = 4, FaceMinusX = 8;
        public static readonly ResidentialModule[] All =
        {
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_01.prefab", Kind = ResidentialModuleKind.Apartment,
                MinX = -5f, MinY = 0f, MinZ = -5f,
                MaxX = 0f, MaxY = 3f, MaxZ = 0.196f,
                Faces = 1, Style = 1, Cells = 1, Floors = 1, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_02.prefab", Kind = ResidentialModuleKind.Apartment,
                MinX = -5.085f, MinY = 0f, MinZ = -5.085f,
                MaxX = 0.085f, MaxY = 3f, MaxZ = 0.129f,
                Faces = 1, Style = 2, Cells = 1, Floors = 1, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_03", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_03.prefab", Kind = ResidentialModuleKind.Apartment,
                MinX = -5.14f, MinY = 0f, MinZ = -5.146f,
                MaxX = 0.14f, MaxY = 3f, MaxZ = 0.351f,
                Faces = 1, Style = 3, Cells = 1, Floors = 1, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Corner_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Corner_01.prefab", Kind = ResidentialModuleKind.ApartmentCorner,
                MinX = -5f, MinY = 0f, MinZ = -5f,
                MaxX = 0.196f, MaxY = 3f, MaxZ = 0.196f,
                Faces = 3, Style = 1, Cells = 1, Floors = 1, OuterCorner = true,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Corner_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Corner_02.prefab", Kind = ResidentialModuleKind.ApartmentCorner,
                MinX = -5.085f, MinY = 0f, MinZ = -5.085f,
                MaxX = 0.129f, MaxY = 3f, MaxZ = 0.129f,
                Faces = 3, Style = 2, Cells = 1, Floors = 1, OuterCorner = true,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Corner_03", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Corner_03.prefab", Kind = ResidentialModuleKind.ApartmentCorner,
                MinX = -5.222f, MinY = 0f, MinZ = -5.224f,
                MaxX = 0.27f, MaxY = 3f, MaxZ = 0.273f,
                Faces = 3, Style = 3, Cells = 1, Floors = 1, OuterCorner = true,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Door_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Door_01.prefab", Kind = ResidentialModuleKind.ApartmentDoor,
                MinX = -5.048f, MinY = 0f, MinZ = -5.048f,
                MaxX = 0.048f, MaxY = 3f, MaxZ = 0.529f,
                Faces = 1, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Door_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Door_02.prefab", Kind = ResidentialModuleKind.ApartmentDoor,
                MinX = -5.057f, MinY = 0f, MinZ = -5.057f,
                MaxX = 0.057f, MaxY = 3f, MaxZ = 0.058f,
                Faces = 1, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Roof_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Roof_01.prefab", Kind = ResidentialModuleKind.Roof,
                MinX = -5.155f, MinY = 0f, MinZ = -5.168f,
                MaxX = 0.155f, MaxY = 0.5f, MaxZ = 0.749f,
                Faces = 1, Style = 1, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 1, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Roof_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Roof_02.prefab", Kind = ResidentialModuleKind.Roof,
                MinX = -5.126f, MinY = 0f, MinZ = -5.152f,
                MaxX = 0.126f, MaxY = 0.744f, MaxZ = 0.336f,
                Faces = 1, Style = 2, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 2, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Roof_03", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Roof_03.prefab", Kind = ResidentialModuleKind.Roof,
                MinX = -5.155f, MinY = 0f, MinZ = -5.168f,
                MaxX = 0.155f, MaxY = 0.744f, MaxZ = 0.456f,
                Faces = 1, Style = 3, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 3, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Roof_Corner_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Roof_Corner_01.prefab", Kind = ResidentialModuleKind.RoofCorner,
                MinX = -5.155f, MinY = 0f, MinZ = -5.168f,
                MaxX = 0.749f, MaxY = 0.5f, MaxZ = 0.749f,
                Faces = 3, Style = 1, Cells = 1, Floors = 0, OuterCorner = true,
                RoofPairStyle = 1, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Roof_Corner_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Roof_Corner_02.prefab", Kind = ResidentialModuleKind.RoofCorner,
                MinX = -5.155f, MinY = 0f, MinZ = -5.168f,
                MaxX = 0.456f, MaxY = 0.744f, MaxZ = 0.456f,
                Faces = 3, Style = 2, Cells = 1, Floors = 0, OuterCorner = true,
                RoofPairStyle = 3, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Roof_Corner_03", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Roof_Corner_03.prefab", Kind = ResidentialModuleKind.RoofCorner,
                MinX = -5.126f, MinY = 0f, MinZ = -5.152f,
                MaxX = 0.336f, MaxY = 0.744f, MaxZ = 0.336f,
                Faces = 3, Style = 3, Cells = 1, Floors = 0, OuterCorner = true,
                RoofPairStyle = 2, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Stack_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Stack_01.prefab", Kind = ResidentialModuleKind.ApartmentStack,
                MinX = -5f, MinY = 0f, MinZ = -5f,
                MaxX = 0f, MaxY = 9f, MaxZ = 0.196f,
                Faces = 1, Style = 1, Cells = 1, Floors = 3, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Stack_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Stack_02.prefab", Kind = ResidentialModuleKind.ApartmentStack,
                MinX = -5.085f, MinY = 0f, MinZ = -5.085f,
                MaxX = 0.085f, MaxY = 9f, MaxZ = 0.129f,
                Faces = 1, Style = 2, Cells = 1, Floors = 3, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Apartment_Stack_03", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Apartment_Stack_03.prefab", Kind = ResidentialModuleKind.ApartmentStack,
                MinX = -5.14f, MinY = 0f, MinZ = -5.146f,
                MaxX = 0.14f, MaxY = 9f, MaxZ = 0.351f,
                Faces = 1, Style = 3, Cells = 1, Floors = 3, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_FireEscape_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_FireEscape_01.prefab", Kind = ResidentialModuleKind.FireEscape,
                MinX = -3.317f, MinY = -0.533f, MinZ = 0f,
                MaxX = -0.066f, MaxY = 0.959f, MaxZ = 1.644f,
                Faces = 0, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 3,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_FireEscape_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_FireEscape_02.prefab", Kind = ResidentialModuleKind.FireEscape,
                MinX = -3.317f, MinY = -0.533f, MinZ = 0f,
                MaxX = -0.066f, MaxY = 3.076f, MaxZ = 1.644f,
                Faces = 0, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 2,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_FireEscape_03", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_FireEscape_03.prefab", Kind = ResidentialModuleKind.FireEscape,
                MinX = -4.899f, MinY = -0.533f, MinZ = 0f,
                MaxX = -0.646f, MaxY = 3.27f, MaxZ = 1.76f,
                Faces = 0, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 1,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Roof_Access_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Roof_Access_01.prefab", Kind = ResidentialModuleKind.RoofAccess,
                MinX = -1.379f, MinY = 0f, MinZ = -1.425f,
                MaxX = 1.379f, MaxY = 2.744f, MaxZ = 1.425f,
                Faces = 0, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_01.prefab", Kind = ResidentialModuleKind.Shop,
                MinX = -5f, MinY = 0f, MinZ = -5f,
                MaxX = 0f, MaxY = 3.054f, MaxZ = 0.536f,
                Faces = 1, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = -2.5f, DoorZ = -0.02f, DoorWidth = 1.7f, DoorHeight = 2.22f, DoorLeaves = 2, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_02.prefab", Kind = ResidentialModuleKind.Shop,
                MinX = -5f, MinY = 0f, MinZ = -5f,
                MaxX = 0f, MaxY = 3.3f, MaxZ = 0.425f,
                Faces = 1, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = -4.03f, DoorZ = -0.21f, DoorWidth = 1.25f, DoorHeight = 2.4f, DoorLeaves = 2, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_03", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_03.prefab", Kind = ResidentialModuleKind.Shop,
                MinX = -10.044f, MinY = 0f, MinZ = -5f,
                MaxX = 0.044f, MaxY = 3.084f, MaxZ = 0.493f,
                Faces = 1, Style = 0, Cells = 2, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = -5f, DoorZ = -0.05f, DoorWidth = 1.9f, DoorHeight = 2.4f, DoorLeaves = 2, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_04", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_04.prefab", Kind = ResidentialModuleKind.Shop,
                MinX = -5.053f, MinY = 0f, MinZ = -5.059f,
                MaxX = 0.053f, MaxY = 3.17f, MaxZ = 0.827f,
                Faces = 1, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = -2.5f, DoorZ = 0.61f, DoorWidth = 1.4f, DoorHeight = 2.62f, DoorLeaves = 1, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_05", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_05.prefab", Kind = ResidentialModuleKind.Shop,
                MinX = -5.054f, MinY = 0f, MinZ = -5.091f,
                MaxX = 0.054f, MaxY = 3f, MaxZ = 0.133f,
                Faces = 1, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = -2.5f, DoorZ = -0.11f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_06", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_06.prefab", Kind = ResidentialModuleKind.Shop,
                MinX = -5.088f, MinY = 0f, MinZ = -5.088f,
                MaxX = 0.088f, MaxY = 3f, MaxZ = 0.789f,
                Faces = 1, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = -4.34f, DoorZ = 0.12f, DoorWidth = 1.1f, DoorHeight = 2.5f, DoorLeaves = 1, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_Corner_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_Corner_01.prefab", Kind = ResidentialModuleKind.ShopCorner,
                MinX = -5.188f, MinY = 0f, MinZ = -5.116f,
                MaxX = 0.188f, MaxY = 3f, MaxZ = 0.283f,
                Faces = 3, Style = 0, Cells = 1, Floors = 0, OuterCorner = true,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = -0.84f, DoorZ = -0.04f, DoorWidth = 1.3f, DoorHeight = 2.05f, DoorLeaves = 2, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_Corner_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_Corner_02.prefab", Kind = ResidentialModuleKind.ShopCorner,
                MinX = -5.166f, MinY = 0f, MinZ = -5.166f,
                MaxX = 0.166f, MaxY = 3f, MaxZ = 0.166f,
                Faces = 3, Style = 0, Cells = 1, Floors = 0, OuterCorner = true,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = -0.77f, DoorZ = -0.77f, DoorWidth = 1.27f, DoorHeight = 2.62f, DoorLeaves = 1, DoorYaw = 45f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_Cover_01", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_Cover_01.prefab", Kind = ResidentialModuleKind.ShopCover,
                MinX = -2.287f, MinY = -0.149f, MinZ = -1.407f,
                MaxX = 2.287f, MaxY = 0.149f, MaxZ = 1.407f,
                Faces = 0, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_Cover_02", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_Cover_02.prefab", Kind = ResidentialModuleKind.ShopCover,
                MinX = -2.353f, MinY = -0.601f, MinZ = -1.618f,
                MaxX = 2.353f, MaxY = 0.601f, MaxZ = 1.618f,
                Faces = 0, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_Cover_03", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_Cover_03.prefab", Kind = ResidentialModuleKind.ShopCover,
                MinX = -2.5f, MinY = -0.673f, MinZ = -1.75f,
                MaxX = 2.5f, MaxY = 1.086f, MaxZ = 1.75f,
                Faces = 0, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_Cover_04", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_Cover_04.prefab", Kind = ResidentialModuleKind.ShopCover,
                MinX = -2.552f, MinY = -0.663f, MinZ = 0f,
                MaxX = 2.552f, MaxY = 0f, MaxZ = 0.732f,
                Faces = 0, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Bld_Shop_Cover_05", Path = "Assets/Synty/PolygonCity/Prefabs/Buildings/SM_Bld_Shop_Cover_05.prefab", Kind = ResidentialModuleKind.ShopCover,
                MinX = -4.662f, MinY = -0.682f, MinZ = -4.662f,
                MaxX = 0.732f, MaxY = 0f, MaxZ = 0.732f,
                Faces = 0, Style = 0, Cells = 1, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_ATM_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_ATM_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.566f, MinY = -0.768f, MinZ = -0.3f,
                MaxX = 0.562f, MaxY = 0.768f, MaxZ = 0.22f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Aircon_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Aircon_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.411f, MinY = 0f, MinZ = 0f,
                MaxX = 0.411f, MaxY = 0.995f, MaxZ = 0.651f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Barrier_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Barrier_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.717f, MinY = 0f, MinZ = -0.332f,
                MaxX = 0.717f, MaxY = 0.983f, MaxZ = 0.332f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Billboard_Roof_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Billboard_Roof_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -2.214f, MinY = 0f, MinZ = -0.806f,
                MaxX = 2.214f, MaxY = 3.063f, MaxZ = 0.806f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Billboard_Sign_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Billboard_Sign_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -2.096f, MinY = 0.823f, MinZ = 0.185f,
                MaxX = 2.096f, MaxY = 2.851f, MaxZ = 0.303f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Billboard_Sign_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Billboard_Sign_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -2.096f, MinY = 0.823f, MinZ = 0.185f,
                MaxX = 2.096f, MaxY = 2.851f, MaxZ = 0.303f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Billboard_Sign_03", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Billboard_Sign_03.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -2.096f, MinY = 0.823f, MinZ = 0.185f,
                MaxX = 2.096f, MaxY = 2.851f, MaxZ = 0.303f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Billboard_Sign_04", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Billboard_Sign_04.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -2.096f, MinY = 0.823f, MinZ = 0.185f,
                MaxX = 2.096f, MaxY = 2.851f, MaxZ = 0.303f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Billboard_Sign_05", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Billboard_Sign_05.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -2.096f, MinY = 0.823f, MinZ = 0.185f,
                MaxX = 2.096f, MaxY = 2.851f, MaxZ = 0.303f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Billboard_Sign_06", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Billboard_Sign_06.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -2.096f, MinY = 0.823f, MinZ = 0.185f,
                MaxX = 2.096f, MaxY = 2.851f, MaxZ = 0.303f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_CardboardBox_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_CardboardBox_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.299f, MinY = 0f, MinZ = -0.299f,
                MaxX = 0.299f, MaxY = 0.505f, MaxZ = 0.299f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_CardboardBox_04", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_CardboardBox_04.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.418f, MinY = 0f, MinZ = -0.525f,
                MaxX = 0.418f, MaxY = 0.702f, MaxZ = 0.525f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Couch_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Couch_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.914f, MinY = 0f, MinZ = -0.565f,
                MaxX = 0.914f, MaxY = 1.06f, MaxZ = 0.565f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Door_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Door_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.772f, MinY = 0f, MinZ = -0.097f,
                MaxX = 0.772f, MaxY = 2.618f, MaxZ = 0.364f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Hydrant_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Hydrant_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.276f, MinY = 0f, MinZ = -0.27f,
                MaxX = 0.276f, MaxY = 1.053f, MaxZ = 0.27f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_LargeSign_Coffee_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_LargeSign_Coffee_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.813f, MinY = 0f, MinZ = -0.813f,
                MaxX = 1.381f, MaxY = 1.346f, MaxZ = 0.813f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_LargeSign_Lollypop_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_LargeSign_Lollypop_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.682f, MinY = -3.18f, MinZ = -0.256f,
                MaxX = 1.682f, MaxY = 3.18f, MaxZ = 0.256f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_LargeSign_Noodles_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_LargeSign_Noodles_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.474f, MinY = -0.096f, MinZ = -1.314f,
                MaxX = 1.474f, MaxY = 3.506f, MaxZ = 1.201f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_LargeSign_Pizza_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_LargeSign_Pizza_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.684f, MinY = 0f, MinZ = -1.478f,
                MaxX = 1.684f, MaxY = 0.562f, MaxZ = 1.478f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Phones_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Phones_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.317f, MinY = 0f, MinZ = -0.523f,
                MaxX = 1.317f, MaxY = 2.501f, MaxZ = 0.523f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Pipe_Preset_03", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Pipe_Preset_03.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.414f, MinY = 0f, MinZ = 0f,
                MaxX = 1.414f, MaxY = 4.243f, MaxZ = 0.498f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Pipe_Small_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Pipe_Small_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.128f, MinY = 0f, MinZ = -0.119f,
                MaxX = 0.023f, MaxY = 4f, MaxZ = 0.275f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Pipe_Small_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Pipe_Small_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.626f, MinY = 0f, MinZ = -0.119f,
                MaxX = -0.283f, MaxY = 3.596f, MaxZ = 0.275f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_PlanterWindow_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_PlanterWindow_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.494f, MinY = 0f, MinZ = -0.068f,
                MaxX = 0.494f, MaxY = 0.743f, MaxZ = 0.301f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_PlanterWindow_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_PlanterWindow_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.452f, MinY = 0f, MinZ = -0.039f,
                MaxX = 0.418f, MaxY = 0.743f, MaxZ = 0.293f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Planter_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Planter_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.151f, MinY = 0f, MinZ = -0.35f,
                MaxX = 1.151f, MaxY = 0.81f, MaxZ = 0.35f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Planter_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Planter_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.756f, MinY = 0f, MinZ = -0.231f,
                MaxX = 0.756f, MaxY = 0.782f, MaxZ = 0.231f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Poster_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Poster_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.328f, MinY = 0.122f, MinZ = 0.006f,
                MaxX = 0.328f, MaxY = 1.078f, MaxZ = 0.044f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Poster_03", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Poster_03.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.328f, MinY = 0.122f, MinZ = 0.006f,
                MaxX = 0.328f, MaxY = 1.078f, MaxZ = 0.044f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Poster_Frame_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Poster_Frame_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.418f, MinY = 0f, MinZ = -0.048f,
                MaxX = 0.418f, MaxY = 1.19f, MaxZ = 0.152f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_PotPlant_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_PotPlant_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.283f, MinY = 0f, MinZ = -0.289f,
                MaxX = 0.283f, MaxY = 0.797f, MaxZ = 0.289f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_PotPlant_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_PotPlant_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.347f, MinY = 0f, MinZ = -0.32f,
                MaxX = 0.347f, MaxY = 1.555f, MaxZ = 0.32f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_PowerBox_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_PowerBox_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.986f, MinY = 0f, MinZ = -0.415f,
                MaxX = 0.986f, MaxY = 1.903f, MaxZ = 0.415f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Roof_Aircon_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Roof_Aircon_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.474f, MinY = 0f, MinZ = -0.234f,
                MaxX = 0.474f, MaxY = 0.592f, MaxZ = 0.234f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Roof_Aircon_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Roof_Aircon_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.793f, MinY = 0f, MinZ = -0.399f,
                MaxX = 0.793f, MaxY = 1.073f, MaxZ = 0.399f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Roof_Aircon_03", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Roof_Aircon_03.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.773f, MinY = 0f, MinZ = -0.5f,
                MaxX = 0.773f, MaxY = 1.05f, MaxZ = 0.5f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_SatDish_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_SatDish_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.605f, MinY = 0f, MinZ = -0.2f,
                MaxX = 0.605f, MaxY = 1.344f, MaxZ = 0.482f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_SecurityCamera_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_SecurityCamera_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.203f, MinY = -0.308f, MinZ = 0f,
                MaxX = 0.203f, MaxY = 0.209f, MaxZ = 0.641f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_SecurityCamera_Arm_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_SecurityCamera_Arm_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.139f, MinY = -0.065f, MinZ = 0f,
                MaxX = 0.139f, MaxY = 0.424f, MaxZ = 0.894f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_ShopInterior_Desk_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_ShopInterior_Desk_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.247f, MinY = 0f, MinZ = -0.618f,
                MaxX = 1.247f, MaxY = 1.247f, MaxZ = 0.661f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_ShopInterior_Shelf_03", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_ShopInterior_Shelf_03.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.609f, MinY = 0f, MinZ = -0.133f,
                MaxX = 0.609f, MaxY = 0.784f, MaxZ = 0.133f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_ShopInterior_Table_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_ShopInterior_Table_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.592f, MinY = 0f, MinZ = -0.585f,
                MaxX = 0.592f, MaxY = 0.948f, MaxZ = 0.585f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sidewalk_Panel_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sidewalk_Panel_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.222f, MinY = 0f, MinZ = -0.219f,
                MaxX = 0.222f, MaxY = 0.06f, MaxZ = 0.219f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Attachment_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Attachment_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.107f, MinY = -0.369f, MinZ = 0f,
                MaxX = 0.107f, MaxY = 0.296f, MaxZ = 0.342f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Attachment_03", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Attachment_03.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.312f, MinY = -0.29f, MinZ = 0f,
                MaxX = 0.312f, MaxY = 0.29f, MaxZ = 1.217f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Barber_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Barber_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.158f, MinY = 0f, MinZ = 0f,
                MaxX = 0.158f, MaxY = 0.948f, MaxZ = 0.474f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Cafe_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Cafe_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.674f, MinY = -0.277f, MinZ = -0.055f,
                MaxX = 0.674f, MaxY = 0.277f, MaxZ = 0.055f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Chinese_Noodles_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Chinese_Noodles_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.427f, MinY = -0.253f, MinZ = 0f,
                MaxX = 0.427f, MaxY = 0.253f, MaxZ = 0.179f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_DeliPizza_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_DeliPizza_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.15f, MinY = -0.775f, MinZ = -0.07f,
                MaxX = 0.15f, MaxY = 0.775f, MaxZ = 0.07f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_GiveWay_03", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_GiveWay_03.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.475f, MinY = 0f, MinZ = -0.062f,
                MaxX = 0.475f, MaxY = 2.217f, MaxZ = 0.066f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Hotel_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Hotel_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.706f, MinY = -0.329f, MinZ = -0.158f,
                MaxX = 0.561f, MaxY = 3.472f, MaxZ = 0.142f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Parking_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Parking_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.221f, MinY = 0f, MinZ = -0.062f,
                MaxX = 0.221f, MaxY = 1.717f, MaxZ = 0.057f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Pizza_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Pizza_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.105f, MinY = 0f, MinZ = -0.072f,
                MaxX = 1.105f, MaxY = 0.704f, MaxZ = 0.072f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Pub_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Pub_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.565f, MinY = 0f, MinZ = -0.056f,
                MaxX = 0.565f, MaxY = 0.547f, MaxZ = 0.056f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Street_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Street_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.64f, MinY = -0.012f, MinZ = -0.183f,
                MaxX = 0.64f, MaxY = 0.012f, MaxZ = 0.183f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_Warning_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_Warning_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.406f, MinY = 0f, MinZ = -0.027f,
                MaxX = 0.406f, MaxY = 0.458f, MaxZ = 0.027f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Sign_XXX_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Sign_XXX_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.074f, MinY = 0f, MinZ = -0.105f,
                MaxX = 1.074f, MaxY = 0.945f, MaxZ = 0.105f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Skip_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Skip_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.215f, MinY = 0f, MinZ = -0.655f,
                MaxX = 1.214f, MaxY = 2.916f, MaxZ = 0.655f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Skip_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Skip_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.215f, MinY = 0f, MinZ = -0.655f,
                MaxX = 1.214f, MaxY = 1.847f, MaxZ = 0.663f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Skylight_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Skylight_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -1.93f, MinY = 0f, MinZ = -0.789f,
                MaxX = 1.93f, MaxY = 0.779f, MaxZ = 0.789f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Table_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Table_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.599f, MinY = 0f, MinZ = -0.599f,
                MaxX = 0.599f, MaxY = 0.588f, MaxZ = 0.599f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_TrashBag_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_TrashBag_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.306f, MinY = 0f, MinZ = -0.415f,
                MaxX = 0.306f, MaxY = 0.905f, MaxZ = 0.415f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_TrashBag_03", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_TrashBag_03.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.355f, MinY = 0f, MinZ = -0.425f,
                MaxX = 0.355f, MaxY = 0.766f, MaxZ = 0.425f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_TrashCan_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_TrashCan_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.366f, MinY = -0.434f, MinZ = -0.366f,
                MaxX = 0.366f, MaxY = 0.434f, MaxZ = 0.366f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_TrashCan_Lid_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_TrashCan_Lid_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.384f, MinY = -0.101f, MinZ = -0.38f,
                MaxX = 0.384f, MaxY = 0.101f, MaxZ = 0.38f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Vents_Corner_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Vents_Corner_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.434f, MinY = 0f, MinZ = 0f,
                MaxX = 2.5f, MaxY = 0.803f, MaxZ = 2.934f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Vents_Corner_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Vents_Corner_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.434f, MinY = 0f, MinZ = 0f,
                MaxX = 2.5f, MaxY = 0.803f, MaxZ = 2.934f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Vents_End_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Vents_End_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.46f, MinY = 0f, MinZ = 0f,
                MaxX = 0.46f, MaxY = 0.803f, MaxZ = 1.088f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Vents_Exhaust_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Vents_Exhaust_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.434f, MinY = 0f, MinZ = 0f,
                MaxX = 0.434f, MaxY = 1.63f, MaxZ = 2.727f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Vents_Straight_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Vents_Straight_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.434f, MinY = 0f, MinZ = 0f,
                MaxX = 0.434f, MaxY = 0.803f, MaxZ = 2.5f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Vents_Transition_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Vents_Transition_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.877f, MinY = 0f, MinZ = 0f,
                MaxX = 0.877f, MaxY = 0.803f, MaxZ = 2.5f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Washingline_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Washingline_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.007f, MinY = -1.168f, MinZ = -0.099f,
                MaxX = 5.198f, MaxY = 0f, MaxZ = 0.057f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Washingline_02", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Washingline_02.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.007f, MinY = -1.384f, MinZ = -0.112f,
                MaxX = 5.198f, MaxY = 0f, MaxZ = 0.077f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Washingline_03", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Washingline_03.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.007f, MinY = -1.295f, MinZ = -0.122f,
                MaxX = 5.198f, MaxY = 0f, MaxZ = 0.071f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
            new ResidentialModule
            {
                Name = "SM_Prop_Window_01", Path = "Assets/Synty/PolygonCity/Prefabs/Props/SM_Prop_Window_01.prefab", Kind = ResidentialModuleKind.Decor,
                MinX = -0.652f, MinY = 0f, MinZ = 0f,
                MaxX = 0.652f, MaxY = 2.313f, MaxZ = 0.37f,
                Faces = 0, Style = 0, Cells = 0, Floors = 0, OuterCorner = false,
                RoofPairStyle = 0, EscapeOrder = 0,
                DoorX = 0f, DoorZ = 0f, DoorWidth = 0f, DoorHeight = 0f, DoorLeaves = 0, DoorYaw = 0f,
            },
        };

        public static ResidentialModule Find(string name)
        {
            if (string.IsNullOrEmpty(name)) return null;
            for (int i = 0; i < All.Length; i++)
                if (string.Equals(All[i].Name, name, StringComparison.OrdinalIgnoreCase)) return All[i];
            return null;
        }

        public static readonly string[] Unresolved =
        {
        };
    }
}
