// GENERATED by Tools/City/Residential/Bake Named Buildings.
// Every figure here was measured off the buildings named residential1..N, the
// parks named park1..N and the named storefronts in Assets/Scenes/CoreHarvest.unity.
// Do not edit by hand - re-run the harvest.
//
// A plan row reads west to east; the FIRST row is the NORTH edge, so the table
// looks the way the block looks from above with north up.
//   '#' the building stands on this cell   'f' its own forecourt: stoop, pit, garden
//   ':' forecourt that drops below -0.6 m (no floor slab under it)
//   ',' building whose own cell drops below -0.6 m
//   '.' nothing - the block's to use

using System.Collections.Generic;
using System.Linq;

namespace RoadDemo
{
    /// <summary>What a residential unit is: its footprint on the 5 m raster, which
    /// of its sides open onto a street, and what hangs over the pavement.</summary>
    public sealed class ResidentialUnit
    {
        public string Name;
        public int CW, CD;
        /// <summary>North row first, west to east. See the key at the top of this file.</summary>
        public string[] Plan;
        /// <summary>South, east, north, west.</summary>
        public bool[] Face;
        public int[] Doors, Shops, Stoops;
        /// <summary>What reaches out past the footprint on each side, metres.</summary>
        public float[] Over;
        public int Trees, Pieces;
        public float MaxH;
        /// <summary>The lowest its walls and stoops go: the level a pit's floor is laid at.</summary>
        public float Floor;
        public ResidentialKind Kind;

        public bool Wall(int i, int j) => At(i, j) == '#' || At(i, j) == ',';
        public bool Yard(int i, int j) => At(i, j) == 'f' || At(i, j) == ':';
        public bool Pit(int i, int j) => At(i, j) == ':' || At(i, j) == ',';
        public bool Filled(int i, int j) => At(i, j) != '.';

        /// <summary>The cell at (i east, j north), reading the plan bottom row first.</summary>
        char At(int i, int j) =>
            i < 0 || j < 0 || i >= CW || j >= CD ? '.' : Plan[CD - 1 - j][i];
    }

    /// <summary>Row, corner, through and island are houses. A park is a fenced square of
    /// grass with its own paths and benches; a storefront is a shop with living over it,
    /// which stands in a gap in the row and gets tables in front.</summary>
    public enum ResidentialKind { Row, Corner, Through, Island, Park, Storefront }

    public static class ResidentialUnits
    {
        public static IEnumerable<ResidentialUnit> Houses =>
            All.Where(u => u.Kind != ResidentialKind.Park && u.Kind != ResidentialKind.Storefront);
        public static IEnumerable<ResidentialUnit> Parks => All.Where(u => u.Kind == ResidentialKind.Park);
        public static IEnumerable<ResidentialUnit> Storefronts => All.Where(u => u.Kind == ResidentialKind.Storefront);

        public static readonly ResidentialUnit[] All =
        {
            new ResidentialUnit
            {
                Name = "residential-01", CW = 5, CD = 4,
                Kind = ResidentialKind.Corner,
                MaxH = 15.6f, Floor = 0.00f, Trees = 0, Pieces = 154,
                Plan = new[]
                {
                    "#####",
                    "#####",
                    "##...",
                    "##...",
                },
                Face = new[] { false, false, true, true },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 0, 1, 3, 4 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 0.73f, 0.47f, 1.97f, 2.03f },
            },
            new ResidentialUnit
            {
                Name = "residential-02", CW = 8, CD = 5,
                Kind = ResidentialKind.Corner,
                MaxH = 18.6f, Floor = 0.00f, Trees = 0, Pieces = 273,
                Plan = new[]
                {
                    "##......",
                    "##......",
                    "##......",
                    "####.###",
                    "########",
                },
                Face = new[] { true, false, false, true },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 6, 1, 1, 3 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.76f, 1.76f, 0.46f, 1.68f },
            },
            new ResidentialUnit
            {
                Name = "residential-03", CW = 9, CD = 5,
                Kind = ResidentialKind.Corner,
                MaxH = 18.6f, Floor = 0.00f, Trees = 0, Pieces = 306,
                Plan = new[]
                {
                    "##.......",
                    "##.......",
                    "##.......",
                    "#########",
                    "#########",
                },
                Face = new[] { true, false, false, true },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 7, 1, 1, 3 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 3.25f, 1.76f, 0.73f, 1.76f },
            },
            new ResidentialUnit
            {
                Name = "residential-04", CW = 5, CD = 5,
                Kind = ResidentialKind.Corner,
                MaxH = 15.2f, Floor = -1.50f, Trees = 6, Pieces = 111,
                Plan = new[]
                {
                    ":::::",
                    "####:",
                    "####:",
                    "..##:",
                    "..##:",
                },
                Face = new[] { false, true, true, false },
                Doors = new[] { 1, 3, 3, 0 },
                Shops = new[] { 0, 0, 0, 0 },
                Stoops = new[] { 0, 5, 3, 0 },
                Over = new[] { 1.14f, 0.13f, 0.13f, 1.76f },
            },
            new ResidentialUnit
            {
                Name = "residential-05", CW = 4, CD = 9,
                Kind = ResidentialKind.Through,
                MaxH = 16.7f, Floor = -1.50f, Trees = 4, Pieces = 126,
                Plan = new[]
                {
                    "::::",
                    ":##:",
                    ":##:",
                    ":##:",
                    ":##:",
                    ":##:",
                    ":##:",
                    ":##:",
                    "::::",
                },
                Face = new[] { false, true, false, true },
                Doors = new[] { 1, 6, 1, 6 },
                Shops = new[] { 0, 0, 0, 0 },
                Stoops = new[] { 1, 6, 1, 8 },
                Over = new[] { 0.00f, 0.13f, 0.00f, 0.13f },
            },
            new ResidentialUnit
            {
                Name = "residential-06", CW = 10, CD = 9,
                Kind = ResidentialKind.Corner,
                MaxH = 18.2f, Floor = 0.00f, Trees = 0, Pieces = 236,
                Plan = new[]
                {
                    "##########",
                    "##########",
                    "........##",
                    "........##",
                    "........##",
                    ".........#",
                    "........##",
                    "........##",
                    "........##",
                },
                Face = new[] { false, true, true, false },
                Doors = new[] { 0, 4, 2, 0 },
                Shops = new[] { 1, 4, 6, 1 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.76f, 1.76f, 1.76f, 0.27f },
            },
            new ResidentialUnit
            {
                Name = "residential-07", CW = 2, CD = 5,
                Kind = ResidentialKind.Island,
                MaxH = 15.6f, Floor = 0.00f, Trees = 0, Pieces = 109,
                Plan = new[]
                {
                    "##",
                    "##",
                    "##",
                    "##",
                    "##",
                },
                Face = new[] { true, true, false, true },
                Doors = new[] { 0, 1, 0, 0 },
                Shops = new[] { 2, 2, 1, 3 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.74f, 1.84f, 0.46f, 1.68f },
            },
            new ResidentialUnit
            {
                Name = "residential-08", CW = 4, CD = 2,
                Kind = ResidentialKind.Through,
                MaxH = 18.6f, Floor = 0.00f, Trees = 0, Pieces = 123,
                Plan = new[]
                {
                    ".###",
                    "####",
                },
                Face = new[] { true, false, true, false },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 2, 1, 3, 0 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.76f, 1.76f, 1.78f, 0.75f },
            },
            new ResidentialUnit
            {
                Name = "residential-10", CW = 3, CD = 3,
                Kind = ResidentialKind.Row,
                MaxH = 15.6f, Floor = 0.00f, Trees = 0, Pieces = 95,
                Plan = new[]
                {
                    "##.",
                    "###",
                    "###",
                },
                Face = new[] { true, false, false, false },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 3, 0, 0, 1 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.74f, 1.40f, 0.72f, 1.68f },
            },
            new ResidentialUnit
            {
                Name = "residential-11", CW = 3, CD = 2,
                Kind = ResidentialKind.Row,
                MaxH = 15.6f, Floor = -0.03f, Trees = 0, Pieces = 73,
                Plan = new[]
                {
                    "###",
                    "###",
                },
                Face = new[] { false, false, true, false },
                Doors = new[] { 1, 0, 0, 0 },
                Shops = new[] { 0, 1, 2, 0 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.65f, 0.57f, 1.81f, 0.81f },
            },
            new ResidentialUnit
            {
                Name = "residential-12", CW = 3, CD = 2,
                Kind = ResidentialKind.Row,
                MaxH = 15.2f, Floor = -0.03f, Trees = 0, Pieces = 69,
                Plan = new[]
                {
                    "###",
                    "###",
                },
                Face = new[] { false, false, true, false },
                Doors = new[] { 1, 0, 0, 0 },
                Shops = new[] { 0, 1, 2, 0 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.65f, 0.57f, 1.81f, 0.81f },
            },
            new ResidentialUnit
            {
                Name = "residential-13", CW = 4, CD = 2,
                Kind = ResidentialKind.Row,
                MaxH = 17.1f, Floor = 0.00f, Trees = 0, Pieces = 118,
                Plan = new[]
                {
                    ".###",
                    "####",
                },
                Face = new[] { false, false, true, false },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 1, 1, 3, 0 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.76f, 1.76f, 1.78f, 0.75f },
            },
            new ResidentialUnit
            {
                Name = "residential-15", CW = 3, CD = 3,
                Kind = ResidentialKind.Row,
                MaxH = 15.2f, Floor = 0.00f, Trees = 0, Pieces = 88,
                Plan = new[]
                {
                    "##.",
                    "###",
                    "###",
                },
                Face = new[] { true, false, false, false },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 3, 0, 0, 1 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 0.72f, 1.40f, 0.72f, 1.68f },
            },
            new ResidentialUnit
            {
                Name = "residential-16", CW = 2, CD = 5,
                Kind = ResidentialKind.Island,
                MaxH = 15.2f, Floor = 0.00f, Trees = 0, Pieces = 103,
                Plan = new[]
                {
                    "##",
                    "##",
                    "##",
                    "##",
                    "##",
                },
                Face = new[] { true, true, false, true },
                Doors = new[] { 0, 1, 0, 0 },
                Shops = new[] { 2, 2, 1, 3 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 1.74f, 1.84f, 0.46f, 1.68f },
            },
            new ResidentialUnit
            {
                Name = "park-01", CW = 4, CD = 4,
                Kind = ResidentialKind.Park,
                MaxH = 4.9f, Floor = -0.03f, Trees = 6, Pieces = 93,
                Plan = new[]
                {
                    "####",
                    "####",
                    "####",
                    "####",
                },
                Face = new[] { false, false, false, false },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 0, 0, 0, 0 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 0.36f, 0.36f, 0.36f, 0.36f },
            },
            new ResidentialUnit
            {
                Name = "park-02", CW = 7, CD = 3,
                Kind = ResidentialKind.Park,
                MaxH = 4.9f, Floor = -0.03f, Trees = 12, Pieces = 113,
                Plan = new[]
                {
                    "#######",
                    "#######",
                    "#######",
                },
                Face = new[] { false, false, false, false },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 0, 0, 0, 0 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 0.36f, 0.36f, 0.36f, 0.36f },
            },
            new ResidentialUnit
            {
                Name = "pizzapub", CW = 1, CD = 2,
                Kind = ResidentialKind.Storefront,
                MaxH = 9.0f, Floor = 0.00f, Trees = 0, Pieces = 15,
                Plan = new[]
                {
                    "#",
                    "#",
                },
                Face = new[] { true, false, false, true },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 1, 0, 0, 1 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 0.46f, 0.19f, 0.46f, 0.54f },
            },
            new ResidentialUnit
            {
                Name = "pizzapub2", CW = 2, CD = 2,
                Kind = ResidentialKind.Storefront,
                MaxH = 8.6f, Floor = 0.00f, Trees = 0, Pieces = 20,
                Plan = new[]
                {
                    "##",
                    "##",
                },
                Face = new[] { true, false, true, false },
                Doors = new[] { 0, 0, 0, 0 },
                Shops = new[] { 2, 0, 2, 0 },
                Stoops = new[] { 0, 0, 0, 0 },
                Over = new[] { 0.46f, 0.85f, 0.75f, 0.88f },
            },
        };
    }
}
