using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace LivingCity.EditorTools
{
    /// <summary>One member of a saved block: a Catalog/Buildings/Blocks prefab by NAME
    /// (never by guid - the catalog rebuild regenerates every guid), placed in the
    /// block's own frame.</summary>
    [System.Serializable]
    public sealed class BlockMemberData
    {
        public string prefab;
        public Vector3 pos;
        public float yaw;
        public bool mirrorX;
    }

    /// <summary>One dressing prop of a saved block, by full asset path.</summary>
    [System.Serializable]
    public sealed class BlockPropData
    {
        public string path;
        public Vector3 pos;
        public float yaw;

        /// <summary>Its scale, which for a ground tile is the whole point of it: the floor
        /// pass lays one tile stretched over a rectangle instead of forty at their natural
        /// size. Read through <see cref="Scale"/>, never directly.</summary>
        public Vector3 scale = Vector3.one;

        /// <summary>The scale to stand it up at. A recipe written before scales were
        /// recorded has none, and a zero would place an invisible prop - both mean
        /// "unscaled".</summary>
        public Vector3 Scale => scale.sqrMagnitude < 0.0001f ? Vector3.one : scale;
    }

    /// <summary>
    /// A block the user composed on a lot pad, in the same frame the hand-dictated
    /// recipes in <see cref="SyntyCityBlocks"/> use: the anchor is the pad centre at
    /// y = 0, turned through the showroom's 180 baseline.
    /// </summary>
    [System.Serializable]
    public sealed class BlockRecipeData
    {
        public string name;
        public string lot;          // lot pad code the block was composed on, e.g. "A1"
        public float lotWidth;
        public float lotDepth;
        public List<BlockMemberData> members = new();
        public List<BlockPropData> props = new();
    }

    /// <summary>
    /// Where composed blocks actually SURVIVE. The catalog scene is regenerated by
    /// every catalog build (and the lot pads are redrawn under one root that gets
    /// destroyed first), so an arrangement that lives only in the scene is gone on
    /// the next rebuild - which is exactly how a dragged-in building went missing.
    ///
    /// A capture writes one JSON per block here instead: named members, named props,
    /// offsets in the block's own frame. The folder sits OUTSIDE Assets/CityKit/Catalog
    /// (which the catalog build deletes wholesale) and outside Blocks (which holds the
    /// bakes), so nothing downstream can wipe it. SyntyCityBlocks bakes these together
    /// with its hand-dictated table, and BlockLotCapture can lay them back out on pads.
    /// </summary>
    public static class BlockRecipeStore
    {
        public const string Dir = SyntyKitExtractor.KitDir + "/BlockRecipes";

        public static string PathOf(string name) => $"{Dir}/{Sanitise(name)}.json";

        /// <summary>Block names become file names and prefab names - keep them to what
        /// both can carry, and never let one escape its folder.</summary>
        public static string Sanitise(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                return "block";
            var clean = new string(name.Trim()
                .Select(c => char.IsLetterOrDigit(c) || c is '-' or '_' ? c : '-').ToArray());
            return clean.Trim('-').Length == 0 ? "block" : clean.Trim('-');
        }

        public static List<BlockRecipeData> LoadAll()
        {
            var list = new List<BlockRecipeData>();
            if (!Directory.Exists(Dir))
                return list;

            foreach (var file in Directory.GetFiles(Dir, "*.json").OrderBy(f => f, System.StringComparer.Ordinal))
            {
                var recipe = Read(file);
                if (recipe != null)
                    list.Add(recipe);
            }
            return list;
        }

        public static BlockRecipeData Load(string name) => Read(PathOf(name));

        /// <summary>Whether a block of this name is already saved - the capture window
        /// asks this on every repaint, so it never touches the file itself.</summary>
        public static bool Exists(string name) => File.Exists(PathOf(name));

        static BlockRecipeData Read(string path)
        {
            if (!File.Exists(path))
                return null;
            try
            {
                var recipe = JsonUtility.FromJson<BlockRecipeData>(File.ReadAllText(path));
                if (recipe == null || string.IsNullOrEmpty(recipe.name))
                {
                    Debug.LogWarning($"[Blocks] '{path}' is not a block recipe - skipped.");
                    return null;
                }
                recipe.members ??= new List<BlockMemberData>();
                recipe.props ??= new List<BlockPropData>();
                return recipe;
            }
            catch (System.Exception e)
            {
                Debug.LogWarning($"[Blocks] '{path}' could not be read: {e.Message}");
                return null;
            }
        }

        public static void Save(BlockRecipeData recipe)
        {
            EnsureFolder();
            recipe.name = Sanitise(recipe.name);
            var path = PathOf(recipe.name);
            File.WriteAllText(path, JsonUtility.ToJson(recipe, prettyPrint: true));
            AssetDatabase.ImportAsset(path);
        }

        /// <summary>
        /// The asset a dressing row names, however it names it. Two shapes reach this:
        /// a hand-dictated row carries a bare prefab name and needs ".prefab" put on,
        /// while a captured row carries the real asset path - and that path is NOT always
        /// a prefab. The PalmCity prefabs are variants of their own fbx, so a capture
        /// resolving through to the original source wrote "Models/SM_x.fbx"; appending to
        /// that gave "SM_x.fbx.prefab", which loads as nothing. That is what dropped every
        /// PalmCity prop out of the bake, the whole auto floor among them.
        ///
        /// So: take the path as it stands first, and only fall back to adding the
        /// extension. <paramref name="tried"/> is what to name in an error.
        /// </summary>
        public static GameObject LoadProp(string path, out string tried)
        {
            tried = path;
            if (string.IsNullOrEmpty(path))
                return null;

            var asset = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            if (asset)
                return asset;

            tried = path + ".prefab";
            return AssetDatabase.LoadAssetAtPath<GameObject>(tried);
        }

        public static void Delete(string name)
        {
            var path = PathOf(name);
            if (File.Exists(path))
                AssetDatabase.DeleteAsset(path);
        }

        static void EnsureFolder()
        {
            if (!AssetDatabase.IsValidFolder(SyntyKitExtractor.KitDir))
                AssetDatabase.CreateFolder("Assets", "CityKit");
            if (!AssetDatabase.IsValidFolder(Dir))
                AssetDatabase.CreateFolder(SyntyKitExtractor.KitDir, "BlockRecipes");
        }
    }
}
