using UnityEngine;
using LivingCity.Data;

namespace LivingCity.Generation
{
    /// <summary>
    /// Drives generation. Deliberately usable from both play mode and the editor window
    /// (Tools/City/Generate) so there is exactly one code path producing the city - the
    /// editor route only swaps in a PrefabUtility-based spawn function.
    /// </summary>
    public sealed class CityBuilder : MonoBehaviour
    {
        public const string GeneratedRootName = "Generated City";

        [SerializeField] CityConfig config;
        [SerializeField] PrefabDatabase prefabs;

        [Tooltip("Leave off once the city is generated into the scene and saved - " +
                 "runtime regeneration exists for testing, not for shipping.")]
        [SerializeField] bool buildOnStart;

        [Header("Layers to generate")]
        [Tooltip("Turn these off to isolate a problem - roads alone is the fastest way to " +
                 "check the path graph without buildings and props cluttering the gizmos.")]
        [SerializeField] bool buildBuildings = true;
        [SerializeField] bool buildProps = true;
        [SerializeField] bool buildParkedCars = true;

        public CityConfig Config => config;
        public PrefabDatabase Prefabs => prefabs;
        public CityGrid Grid { get; private set; }

        void Start()
        {
            if (buildOnStart)
                Build();
        }

        public Transform Build(SpawnPrefab spawn = null)
        {
            if (!config || !prefabs)
            {
                Debug.LogError("[CityBuilder] Assign both a CityConfig and a PrefabDatabase before generating.", this);
                return null;
            }

            Clear();

            Grid = CityGenerator.Generate(config);

            // Zoning runs before anything is placed because two layers need the answer: the
            // ground has to know a park is grass and a car park is asphalt, and the buildings
            // have to know which kit to draw from. Deriving it twice would eventually pave a park.
            ZonePlanner.Assign(Grid, prefabs, config);

            var root = new GameObject(GeneratedRootName);
            root.transform.SetParent(transform, false);

            // Both ride along in the saved scene. Added here rather than in the scene setup so
            // a city generated by any route - editor window, runtime rebuild - carries them.
            //
            // MapEdgeGates finds where the streets cross the outline of the map, which is where
            // traffic enters and leaves. DeadEndStitcher repairs the same lanes with a U-turn,
            // for anything that reaches one without meaning to. Order between them does not
            // matter: the gates are measured geometrically, not from the path links.
            root.AddComponent<MapEdgeGates>();
            root.AddComponent<DeadEndStitcher>();

            // Roads first, and all in one synchronous pass - see RoadNetworkBuilder.Build.
            var roadsParent = Category(root.transform, "Roads");
            var roads = RoadNetworkBuilder.Build(Grid, prefabs, config, roadsParent, spawn);

            // Ground before buildings so the slab is already there to stand on.
            var ground = buildBuildings
                ? GroundPlacer.Build(Grid, prefabs, config, Category(root.transform, "Ground"), spawn)
                : new System.Collections.Generic.List<GameObject>();

            var buildings = buildBuildings
                ? BlockBuilder.Build(Grid, prefabs, config, Category(root.transform, "Buildings"), spawn)
                : new System.Collections.Generic.List<GameObject>();

            // Colour variation is a post-pass over what BlockBuilder placed, deliberately not a
            // parameter threaded through the perimeter walk - placement and appearance have no
            // reason to know about each other.
            BuildingTinter.Apply(buildings, prefabs, config);

            var props = buildProps
                ? StreetPropPlacer.Build(Grid, prefabs, config, Category(root.transform, "Props"), spawn)
                : new System.Collections.Generic.List<GameObject>();

            // Props are passed in as obstacles: parked cars share the verge with the lamps and
            // trees, so the placer needs to know what is already standing there.
            var parked = buildParkedCars
                ? ParkedCarPlacer.Build(Grid, prefabs, config, Category(root.transform, "ParkedCars"), spawn, props)
                : new System.Collections.Generic.List<GameObject>();

            Debug.Log($"[CityBuilder] Generated {config.gridWidth}x{config.gridHeight} city " +
                      $"(seed {config.seed}): {roads.Tiles.Count} tiles, " +
                      $"{roads.TrafficLights.Count} traffic lights, {Grid.BlockCount} blocks, " +
                      $"{ground.Count} ground slabs, {buildings.Count} buildings, " +
                      $"{props.Count} props, {parked.Count} parked cars.\n" +
                      $"[CityBuilder] Zones: {ZonePlanner.Describe(Grid)}");

            return root.transform;
        }

        public void Clear()
        {
            var existing = transform.Find(GeneratedRootName);
            if (!existing)
                return;

            if (Application.isPlaying)
                Destroy(existing.gameObject);
            else
                DestroyImmediate(existing.gameObject);
        }

        public Transform GeneratedRoot => transform.Find(GeneratedRootName);

        static Transform Category(Transform root, string name)
        {
            var category = new GameObject(name);
            category.transform.SetParent(root, false);
            return category.transform;
        }
    }
}
