using UnityEngine;
using LivingCity.Data;

namespace LivingCity.Generation
{
    /// <summary>
    /// Drives generation. Deliberately usable from both play mode and the editor window
    /// (Tools/City/Generate) so there is exactly one code path producing the city - the
    /// editor route only swaps in a PrefabUtility-based spawn function.
    /// </summary>
    public sealed class CityBuilder : MonoBehaviour
    {
        public const string GeneratedRootName = "Generated City";

        [SerializeField] CityConfig config;
        [SerializeField] PrefabDatabase prefabs;

        [Tooltip("Tuning for the works yard dressing. Optional: leave it empty and the yards " +
                 "build with the same defaults the asset ships with, rather than failing.")]
        [SerializeField] IndustrialLotConfig lotConfig;

        [Tooltip("Leave off once the city is generated into the scene and saved - " +
                 "runtime regeneration exists for testing, not for shipping.")]
        [SerializeField] bool buildOnStart;

        [Header("Layers to generate")]
        [Tooltip("Turn these off to isolate a problem - roads alone is the fastest way to " +
                 "check the path graph without buildings and props cluttering the gizmos.")]
        [SerializeField] bool buildBuildings = true;
        [SerializeField] bool buildProps = true;

        public CityConfig Config => config;
        public PrefabDatabase Prefabs => prefabs;
        public CityGrid Grid { get; private set; }

        void Start()
        {
            if (buildOnStart)
                Build();
        }

        public Transform Build(SpawnPrefab spawn = null)
        {
            if (!config || !prefabs)
            {
                Debug.LogError("[CityBuilder] Assign both a CityConfig and a PrefabDatabase before generating.", this);
                return null;
            }

            Clear();

            Grid = CityGenerator.Generate(config);

            // Zoning runs before anything is placed because two layers need the answer: the
            // ground has to know a park is grass and a car park is asphalt, and the buildings
            // have to know which kit to draw from. Deriving it twice would eventually pave a park.
            ZonePlanner.Assign(Grid, prefabs, config);

            var root = new GameObject(GeneratedRootName);
            root.transform.SetParent(transform, false);

            // Both ride along in the saved scene. Added here rather than in the scene setup so
            // a city generated by any route - editor window, runtime rebuild - carries them.
            //
            // MapEdgeGates finds where the streets cross the outline of the map, which is where
            // traffic enters and leaves. DeadEndStitcher repairs the same lanes with a U-turn,
            // for anything that reaches one without meaning to. Order between them does not
            // matter: the gates are measured geometrically, not from the path links.
            root.AddComponent<MapEdgeGates>();
            root.AddComponent<DeadEndStitcher>();

            // Roads first, and all in one synchronous pass - see RoadNetworkBuilder.Build.
            var roadsParent = Category(root.transform, "Roads");
            var roads = RoadNetworkBuilder.Build(Grid, prefabs, config, roadsParent, spawn);

            // Ground before buildings so the slab is already there to stand on.
            var ground = buildBuildings
                ? GroundPlacer.Build(Grid, prefabs, config, Category(root.transform, "Ground"), spawn)
                : new System.Collections.Generic.List<GameObject>();

            // The tinter takes its own list rather than `buildings`: that one collects
            // everything the block placer spawned - parked cars, trees, kiosks - and only
            // placement knows which spawns are buildings and which group each came from,
            // which is what decides the residential/commercial palette split.
            var tintTargets = new System.Collections.Generic.List<BuildingTinter.Target>();

            // Compound gate approaches, filled by the block pass and read by the prop pass -
            // the only way StreetPropPlacer can know where the walls have their holes. Empty
            // when buildings are off, which is correct: no walls, no gates to keep clear.
            var gateKeepOuts = new System.Collections.Generic.List<Bounds>();

            var buildings = buildBuildings
                ? BlockBuilder.Build(Grid, prefabs, config, Category(root.transform, "Buildings"),
                                     spawn, tintTargets, gateKeepOuts)
                : new System.Collections.Generic.List<GameObject>();

            // The works yards, dressed after the compounds they stand in. Its inputs come off the
            // WorksYard markers IndustrialDresser attached - the same generate-in-editor-and-save
            // handoff PoliceStation uses - so this cannot see, and cannot disturb, BlockBuilder's
            // rng. Before the tinter so anything it stands up can still join tintTargets.
            var yards = buildBuildings
                ? IndustrialLotBuilder.Build(root.transform, prefabs, config, lotConfig,
                                             Category(root.transform, "Works Yards"), spawn)
                : new System.Collections.Generic.List<GameObject>();

            BuildingTinter.Apply(tintTargets, prefabs, config);

            // Lamps and street trees only. Nothing parks at the kerb any more - the band they
            // stand in is paved by GroundPlacer's apron rather than left as grass verge.
            var props = buildProps
                ? StreetPropPlacer.Build(Grid, prefabs, config, Category(root.transform, "Props"),
                                         spawn, gateKeepOuts)
                : new System.Collections.Generic.List<GameObject>();

            // Interaction markers last, over the finished hierarchy: benches and shopfronts
            // are spawned from five different places, and one name-matching sweep here is the
            // single hook that covers them all. The markers are data-only components, so they
            // ride into the saved scene and cost nothing when interactions are off.
            //
            // The grid goes with it because street doors need to know which facades front a
            // pavement, and this is the last moment anything knows: CityGrid is not
            // serialized, so Grid is null at Play in a scene that was generated and saved.
            var interactionPoints = InteractionMarkers.Attach(root.transform, Grid);

            // In Play the lamp rig built its lights in Start, against the city that just got
            // replaced - re-wire it here or the new lamps stay dark. In the editor, relight
            // at the configured start hour too: it used to wait for the night preview menu,
            // and every freshly generated city read as "the lamps do not work at all".
            {
                var lampRig = FindAnyObjectByType<Ambient.StreetLampLights>();
                if (lampRig)
                {
                    if (Application.isPlaying)
                        lampRig.Rebuild();
                    else
                        lampRig.ApplyForEditor(Ambient.CityWeather.Nightness(config.startHour));
                }
            }

            Debug.Log($"[CityBuilder] Generated {config.gridWidth}x{config.gridHeight} city " +
                      $"(seed {config.seed}): {roads.Tiles.Count} tiles, " +
                      $"{roads.TrafficLights.Count} traffic lights, {Grid.BlockCount} blocks, " +
                      $"{ground.Count} ground slabs, {buildings.Count} buildings, " +
                      $"{yards.Count} yard surfaces, " +
                      $"{props.Count} props, {interactionPoints} interaction points.\n" +
                      $"[CityBuilder] Zones: {ZonePlanner.Describe(Grid)}");

            return root.transform;
        }

        /// <summary>
        /// Tears the generated city down and returns how many roots it removed.
        ///
        /// Every matching child, not transform.Find's first hit. Find returning one root at a
        /// time is what let them stack: Build calls Clear once and then adds a root, so a second
        /// root never gets removed, it only ever gets pushed down the sibling list. The symptom
        /// is a Clear button that reports success on click after click while the city stays put -
        /// each press was removing one root off a pile.
        ///
        /// The count is returned rather than logged because Build calls Clear on every generate,
        /// and a log here would bury the generation summary.
        /// </summary>
        public int Clear()
        {
            var destroyed = 0;

            // Backwards, because destroying re-indexes the remaining children.
            for (var i = transform.childCount - 1; i >= 0; i--)
            {
                var child = transform.GetChild(i);
                if (!IsGeneratedRoot(child.name)) continue;

                if (Application.isPlaying)
                    Destroy(child.gameObject);
                else
                    DestroyImmediate(child.gameObject);

                destroyed++;
            }

            // The lamp rig hangs its lights under the lamps just destroyed. Torn down even when
            // there was no root: an interrupted earlier clear can leave orphaned lights hanging
            // mid-air where lamps used to stand, and this is the only sweep that removes them.
            var lampRig = FindAnyObjectByType<Ambient.StreetLampLights>();
            if (lampRig)
                lampRig.Teardown();

            return destroyed;
        }

        /// <summary>
        /// Also matches "Generated City (1)" and friends - the name Unity gives a root duplicated
        /// in the hierarchy with Cmd+D. Those are invisible to transform.Find, so before this they
        /// could never be cleared by any route and simply sat there looking like a failed clear.
        /// </summary>
        static bool IsGeneratedRoot(string name) =>
            name == GeneratedRootName || name.StartsWith(GeneratedRootName + " (");

        public Transform GeneratedRoot => transform.Find(GeneratedRootName);

        static Transform Category(Transform root, string name)
        {
            var category = new GameObject(name);
            category.transform.SetParent(root, false);
            return category.transform;
        }
    }
}
