// GENERATED by tools/extract-patches.mjs - do not edit.
// 5x5 9-patch chrome off the CC0 "Waste No Space" GUI sheet (flatus.itch.io).
export const patches = {
  "panelDark": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAGUlEQVR42mPg5xP7j44ZQIS5sQMckyGIjgHbuSIS2AGmqgAAAABJRU5ErkJggg==",
  "panelRaised": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAALklEQVR42mPg5xP7j44ZQISDrdt/c2MHMA0XBAnoqhuDabggSEBVURNMwwXRMQDS4iGgkZO3kgAAAABJRU5ErkJggg==",
  "sunken": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAJUlEQVR42mNgAAJ+PrH/MMwAE1BV1IRjsASI0FU3hmPcgtjMBACQcBvHCNWLkgAAAABJRU5ErkJggg==",
  "buttonNormal": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAM0lEQVR42mNgAAJ+PrH/MMwAE3CwdftvbuwApsESIAIkoKtuDKbhgiABVUVNMI1iBLKZAN1/HNjbZSXdAAAAAElFTkSuQmCC",
  "buttonHover": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAM0lEQVR42mNgAAJ+PrH/MMwAE2ho6PofE54MpsESIAIk4GDrBqbhgiABc2MHMI1iBLKZAL9PIJnkZPijAAAAAElFTkSuQmCC",
  "buttonPressed": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAJUlEQVR42mNgAAJ+PrH/MMwAE1BV1IRjsASI0FU3hmPcgtjMBACQcBvHCNWLkgAAAABJRU5ErkJggg==",
  "buttonDisabled": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAH0lEQVR42mNgAAJVRc3/MMwAE3CwdYNjsATxgtjMBACqSSD7vrry4AAAAABJRU5ErkJggg=="
} as const;
